import type {
  User,
  Cliente,
  Prospecto,
  Proyecto,
  Ticket,
  Campana,
  Transaccion,
  Paquete,
  MetricasDashboard,
} from '@/types';

// ═══════════════════════════════════════════════════════════════════════════
// DATOS DE PRUEBA PARA SYLLET MANAGER
// ═══════════════════════════════════════════════════════════════════════════

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'admin@syllet.com',
    nombre: 'Carlos',
    apellido: 'Mendoza',
    rol: 'admin',
    departamento: 'direccion',
    telefono: '+52 55 1234 5678',
    activo: true,
    fechaCreacion: new Date('2024-01-01'),
    ultimoAcceso: new Date(),
  },
  {
    id: '2',
    email: 'ana.garcia@syllet.com',
    nombre: 'Ana',
    apellido: 'García',
    rol: 'vendedor',
    departamento: 'ventas',
    telefono: '+52 55 2345 6789',
    activo: true,
    fechaCreacion: new Date('2024-02-15'),
    ultimoAcceso: new Date(),
    metaMensual: 150000,
    comisionPorcentaje: 10,
  },
  {
    id: '3',
    email: 'miguel.lopez@syllet.com',
    nombre: 'Miguel',
    apellido: 'López',
    rol: 'vendedor',
    departamento: 'ventas',
    telefono: '+52 55 3456 7890',
    activo: true,
    fechaCreacion: new Date('2024-03-01'),
    ultimoAcceso: new Date(),
    metaMensual: 120000,
    comisionPorcentaje: 10,
  },
  {
    id: '4',
    email: 'laura.martinez@syllet.com',
    nombre: 'Laura',
    apellido: 'Martínez',
    rol: 'operaciones',
    departamento: 'operaciones',
    activo: true,
    fechaCreacion: new Date('2024-01-15'),
  },
  {
    id: '5',
    email: 'roberto.sanchez@syllet.com',
    nombre: 'Roberto',
    apellido: 'Sánchez',
    rol: 'soporte',
    departamento: 'soporte',
    activo: true,
    fechaCreacion: new Date('2024-04-01'),
  },
  {
    id: '6',
    email: 'maria.fernandez@syllet.com',
    nombre: 'María',
    apellido: 'Fernández',
    rol: 'marketing',
    departamento: 'marketing',
    activo: true,
    fechaCreacion: new Date('2024-02-01'),
  },
];

export const mockClientes: Cliente[] = [
  {
    id: '1',
    nombre: 'Juan Pérez',
    empresa: 'Restaurante El Buen Sabor',
    email: 'juan@buensabor.com',
    telefono: '+52 55 1111 2222',
    ciudad: 'Ciudad de México',
    pais: 'México',
    vendedorAsignado: '2',
    origenLead: 'facebook',
    fechaCreacion: new Date('2024-06-15'),
    fechaUltimoContacto: new Date('2024-12-20'),
    valorTotal: 45000,
    proyectosActivos: 1,
  },
  {
    id: '2',
    nombre: 'Patricia Hernández',
    empresa: 'Boutique Elegance',
    email: 'patricia@elegance.com',
    telefono: '+52 33 3333 4444',
    ciudad: 'Guadalajara',
    pais: 'México',
    vendedorAsignado: '3',
    origenLead: 'google',
    fechaCreacion: new Date('2024-07-20'),
    fechaUltimoContacto: new Date('2024-12-18'),
    valorTotal: 85000,
    proyectosActivos: 1,
  },
  {
    id: '3',
    nombre: 'Ricardo Torres',
    empresa: 'Constructora Torres',
    email: 'ricardo@ctorres.com',
    telefono: '+52 81 5555 6666',
    ciudad: 'Monterrey',
    pais: 'México',
    vendedorAsignado: '2',
    origenLead: 'referido',
    fechaCreacion: new Date('2024-08-10'),
    fechaUltimoContacto: new Date('2024-12-15'),
    valorTotal: 120000,
    proyectosActivos: 2,
  },
  {
    id: '4',
    nombre: 'Sofia Ramírez',
    empresa: 'Clínica Dental Sonrisas',
    email: 'sofia@sonrisas.com',
    telefono: '+52 55 7777 8888',
    ciudad: 'Ciudad de México',
    pais: 'México',
    vendedorAsignado: '3',
    origenLead: 'instagram',
    fechaCreacion: new Date('2024-09-05'),
    fechaUltimoContacto: new Date('2024-12-22'),
    valorTotal: 35000,
    proyectosActivos: 1,
  },
  {
    id: '5',
    nombre: 'Fernando Díaz',
    empresa: 'Gimnasio FitLife',
    email: 'fernando@fitlife.mx',
    telefono: '+52 55 9999 0000',
    ciudad: 'Ciudad de México',
    pais: 'México',
    vendedorAsignado: '2',
    origenLead: 'organico',
    fechaCreacion: new Date('2024-10-12'),
    fechaUltimoContacto: new Date('2024-12-21'),
    valorTotal: 55000,
    proyectosActivos: 0,
  },
];

export const mockProspectos: Prospecto[] = [
  {
    id: '1',
    nombre: 'Eduardo Morales',
    empresa: 'Café Morales',
    email: 'eduardo@cafemorales.com',
    telefono: '+52 55 1234 0001',
    etapa: 'lead',
    valorEstimado: 25000,
    probabilidad: 20,
    vendedorId: '2',
    servicioInteres: 'landing_page',
    fechaCreacion: new Date('2024-12-20'),
    fechaUltimaActualizacion: new Date('2024-12-20'),
    seguimientos: [],
  },
  {
    id: '2',
    nombre: 'Carmen Vega',
    empresa: 'Floristería Primavera',
    email: 'carmen@primavera.com',
    telefono: '+52 55 1234 0002',
    etapa: 'contacto',
    valorEstimado: 35000,
    probabilidad: 40,
    vendedorId: '3',
    servicioInteres: 'web_basica',
    fechaCreacion: new Date('2024-12-15'),
    fechaUltimaActualizacion: new Date('2024-12-22'),
    seguimientos: [
      {
        id: '1',
        fecha: new Date('2024-12-18'),
        tipo: 'llamada',
        descripcion: 'Llamada inicial, interesada en página web básica',
        resultado: 'Programada demo para el viernes',
        usuarioId: '3',
      },
    ],
  },
  {
    id: '3',
    nombre: 'Luis Ortega',
    empresa: 'Taller Mecánico Ortega',
    email: 'luis@tallerortega.com',
    telefono: '+52 55 1234 0003',
    etapa: 'cotizacion',
    valorEstimado: 45000,
    probabilidad: 60,
    vendedorId: '2',
    servicioInteres: 'web_profesional',
    fechaCreacion: new Date('2024-12-10'),
    fechaUltimaActualizacion: new Date('2024-12-21'),
    seguimientos: [
      {
        id: '1',
        fecha: new Date('2024-12-12'),
        tipo: 'llamada',
        descripcion: 'Primera llamada, muy interesado',
        usuarioId: '2',
      },
      {
        id: '2',
        fecha: new Date('2024-12-18'),
        tipo: 'reunion',
        descripcion: 'Reunión presencial, se envió cotización',
        usuarioId: '2',
      },
    ],
  },
  {
    id: '4',
    nombre: 'Andrea Campos',
    empresa: 'Pastelería Dulce Encanto',
    email: 'andrea@dulceencanto.com',
    telefono: '+52 55 1234 0004',
    etapa: 'negociacion',
    valorEstimado: 75000,
    probabilidad: 80,
    vendedorId: '3',
    servicioInteres: 'ecommerce',
    fechaCreacion: new Date('2024-12-01'),
    fechaUltimaActualizacion: new Date('2024-12-23'),
    fechaCierreEstimada: new Date('2024-12-28'),
    seguimientos: [],
  },
  {
    id: '5',
    nombre: 'Mario Salinas',
    empresa: 'Inmobiliaria Salinas',
    email: 'mario@inmosalinas.com',
    telefono: '+52 55 1234 0005',
    etapa: 'cierre',
    valorEstimado: 150000,
    probabilidad: 95,
    vendedorId: '2',
    servicioInteres: 'sistema_medida',
    fechaCreacion: new Date('2024-11-15'),
    fechaUltimaActualizacion: new Date('2024-12-22'),
    seguimientos: [],
  },
];

export const mockProyectos: Proyecto[] = [
  {
    id: '1',
    nombre: 'Página Web El Buen Sabor',
    clienteId: '1',
    tipo: 'web_profesional',
    descripcion: 'Página web profesional con menú digital y reservaciones',
    estado: 'en_desarrollo',
    progreso: 65,
    desarrolladorId: '4',
    desarrolladores: ['4'],
    fechaInicio: new Date('2024-11-20'),
    fechaEntregaEstimada: new Date('2024-12-30'),
    presupuesto: 45000,
    prioridad: 'alta',
    checklist: [
      { id: '1', tarea: 'Diseño inicial', completado: true, orden: 1 },
      { id: '2', tarea: 'Maquetación responsive', completado: true, orden: 2 },
      { id: '3', tarea: 'Integración menú digital', completado: true, orden: 3 },
      { id: '4', tarea: 'Sistema de reservaciones', completado: false, orden: 4 },
      { id: '5', tarea: 'Optimización SEO', completado: false, orden: 5 },
      { id: '6', tarea: 'Pruebas finales', completado: false, orden: 6 },
    ],
    archivos: [],
    accesos: [],
  },
  {
    id: '2',
    nombre: 'E-commerce Boutique Elegance',
    clienteId: '2',
    tipo: 'ecommerce',
    descripcion: 'Tienda en línea con catálogo de productos y pasarela de pagos',
    estado: 'en_desarrollo',
    progreso: 40,
    desarrolladorId: '4',
    desarrolladores: ['4'],
    fechaInicio: new Date('2024-12-01'),
    fechaEntregaEstimada: new Date('2025-01-15'),
    presupuesto: 85000,
    prioridad: 'alta',
    checklist: [
      { id: '1', tarea: 'Diseño UI/UX', completado: true, orden: 1 },
      { id: '2', tarea: 'Desarrollo frontend', completado: true, orden: 2 },
      { id: '3', tarea: 'Catálogo de productos', completado: false, orden: 3 },
      { id: '4', tarea: 'Carrito de compras', completado: false, orden: 4 },
      { id: '5', tarea: 'Integración pasarela de pagos', completado: false, orden: 5 },
      { id: '6', tarea: 'Panel de administración', completado: false, orden: 6 },
    ],
    archivos: [],
    accesos: [],
  },
  {
    id: '3',
    nombre: 'Sistema CRM Constructora Torres',
    clienteId: '3',
    tipo: 'sistema_medida',
    descripcion: 'Sistema a medida para gestión de proyectos de construcción',
    estado: 'en_desarrollo',
    progreso: 25,
    desarrolladorId: '4',
    desarrolladores: ['4'],
    fechaInicio: new Date('2024-12-10'),
    fechaEntregaEstimada: new Date('2025-02-28'),
    presupuesto: 120000,
    prioridad: 'media',
    checklist: [
      { id: '1', tarea: 'Análisis de requerimientos', completado: true, orden: 1 },
      { id: '2', tarea: 'Arquitectura del sistema', completado: true, orden: 2 },
      { id: '3', tarea: 'Base de datos', completado: false, orden: 3 },
      { id: '4', tarea: 'Módulo de proyectos', completado: false, orden: 4 },
      { id: '5', tarea: 'Módulo de clientes', completado: false, orden: 5 },
      { id: '6', tarea: 'Reportes y dashboards', completado: false, orden: 6 },
    ],
    archivos: [],
    accesos: [],
  },
  {
    id: '4',
    nombre: 'Landing Page Clínica Sonrisas',
    clienteId: '4',
    tipo: 'landing_page',
    descripcion: 'Landing page con formulario de citas y galería de servicios',
    estado: 'entregado',
    progreso: 100,
    desarrolladorId: '4',
    desarrolladores: ['4'],
    fechaInicio: new Date('2024-11-01'),
    fechaEntregaEstimada: new Date('2024-11-15'),
    fechaEntregaReal: new Date('2024-11-14'),
    presupuesto: 35000,
    prioridad: 'media',
    checklist: [
      { id: '1', tarea: 'Diseño', completado: true, orden: 1 },
      { id: '2', tarea: 'Desarrollo', completado: true, orden: 2 },
      { id: '3', tarea: 'Formulario de contacto', completado: true, orden: 3 },
      { id: '4', tarea: 'Entrega', completado: true, orden: 4 },
    ],
    archivos: [],
    accesos: [],
  },
  {
    id: '5',
    nombre: 'Portal Inmobiliaria Torres',
    clienteId: '3',
    tipo: 'web_profesional',
    descripcion: 'Portal web con catálogo de propiedades y sistema de búsqueda',
    estado: 'pendiente',
    progreso: 0,
    desarrolladores: [],
    fechaInicio: new Date('2025-01-05'),
    fechaEntregaEstimada: new Date('2025-02-15'),
    presupuesto: 65000,
    prioridad: 'baja',
    checklist: [],
    archivos: [],
    accesos: [],
  },
];

export const mockTickets: Ticket[] = [
  {
    id: '1',
    numero: 'TKT-2024-0042',
    clienteId: '1',
    proyectoId: '1',
    asunto: 'Actualizar horarios del restaurante',
    descripcion: 'Necesito actualizar los horarios de atención en la página',
    tipo: 'cambio',
    prioridad: 'media',
    estado: 'abierto',
    asignadoA: '5',
    fechaCreacion: new Date('2024-12-22'),
    fechaActualizacion: new Date('2024-12-22'),
    respuestas: [],
  },
  {
    id: '2',
    numero: 'TKT-2024-0041',
    clienteId: '4',
    proyectoId: '4',
    asunto: 'Formulario no envía correos',
    descripcion: 'Los formularios de contacto no están llegando al correo',
    tipo: 'bug',
    prioridad: 'urgente',
    estado: 'en_progreso',
    asignadoA: '5',
    fechaCreacion: new Date('2024-12-21'),
    fechaActualizacion: new Date('2024-12-22'),
    respuestas: [
      {
        id: '1',
        mensaje: 'Estamos investigando el problema con el servidor de correo',
        usuarioId: '5',
        esCliente: false,
        fechaCreacion: new Date('2024-12-22'),
      },
    ],
  },
  {
    id: '3',
    numero: 'TKT-2024-0040',
    clienteId: '2',
    proyectoId: '2',
    asunto: 'Agregar nuevos productos al catálogo',
    descripcion: 'Necesito agregar 15 productos nuevos a la tienda',
    tipo: 'mejora',
    prioridad: 'baja',
    estado: 'pendiente_cliente',
    asignadoA: '5',
    fechaCreacion: new Date('2024-12-20'),
    fechaActualizacion: new Date('2024-12-21'),
    respuestas: [
      {
        id: '1',
        mensaje: 'Por favor envíenos las fotos y descripciones de los productos',
        usuarioId: '5',
        esCliente: false,
        fechaCreacion: new Date('2024-12-21'),
      },
    ],
  },
];

export const mockCampanas: Campana[] = [
  {
    id: '1',
    nombre: 'Black Friday 2024',
    plataforma: 'facebook',
    tipo: 'conversiones',
    estado: 'finalizada',
    presupuesto: 15000,
    gastoActual: 14500,
    fechaInicio: new Date('2024-11-20'),
    fechaFin: new Date('2024-11-30'),
    leads: 145,
    conversiones: 12,
    cpl: 100,
    roi: 280,
    responsableId: '6',
  },
  {
    id: '2',
    nombre: 'Campaña Navidad',
    plataforma: 'google',
    tipo: 'leads',
    estado: 'activa',
    presupuesto: 20000,
    gastoActual: 8500,
    fechaInicio: new Date('2024-12-01'),
    fechaFin: new Date('2024-12-31'),
    leads: 89,
    conversiones: 5,
    cpl: 95.5,
    roi: 0,
    responsableId: '6',
  },
  {
    id: '3',
    nombre: 'Branding Instagram',
    plataforma: 'instagram',
    tipo: 'awareness',
    estado: 'activa',
    presupuesto: 8000,
    gastoActual: 4200,
    fechaInicio: new Date('2024-12-10'),
    leads: 34,
    conversiones: 2,
    cpl: 123.5,
    roi: 0,
    responsableId: '6',
  },
];

export const mockTransacciones: Transaccion[] = [
  {
    id: '1',
    tipo: 'ingreso',
    categoria: 'venta_proyecto',
    descripcion: 'Anticipo proyecto El Buen Sabor',
    monto: 22500,
    fecha: new Date('2024-11-20'),
    clienteId: '1',
    proyectoId: '1',
    metodoPago: 'transferencia',
    creadoPor: '1',
  },
  {
    id: '2',
    tipo: 'ingreso',
    categoria: 'venta_proyecto',
    descripcion: 'Anticipo E-commerce Boutique Elegance',
    monto: 42500,
    fecha: new Date('2024-12-01'),
    clienteId: '2',
    proyectoId: '2',
    metodoPago: 'transferencia',
    creadoPor: '1',
  },
  {
    id: '3',
    tipo: 'ingreso',
    categoria: 'venta_proyecto',
    descripcion: 'Pago final Landing Page Clínica Sonrisas',
    monto: 17500,
    fecha: new Date('2024-11-14'),
    clienteId: '4',
    proyectoId: '4',
    metodoPago: 'transferencia',
    creadoPor: '1',
  },
  {
    id: '4',
    tipo: 'egreso',
    categoria: 'publicidad',
    descripcion: 'Campaña Facebook Ads - Diciembre',
    monto: 8500,
    fecha: new Date('2024-12-15'),
    creadoPor: '1',
  },
  {
    id: '5',
    tipo: 'egreso',
    categoria: 'herramientas',
    descripcion: 'Suscripción herramientas (Figma, hosting, etc)',
    monto: 3500,
    fecha: new Date('2024-12-01'),
    creadoPor: '1',
  },
];

export const mockPaquetes: Paquete[] = [
  {
    id: '1',
    nombre: 'Landing Page',
    tipo: 'landing_page',
    descripcion: 'Página de aterrizaje optimizada para conversión',
    precio: 15000,
    precioAnterior: 18000,
    caracteristicas: [
      'Diseño personalizado',
      'Responsive (móvil, tablet, desktop)',
      'Formulario de contacto',
      'Optimización SEO básica',
      'Integración WhatsApp',
      'Hosting 1 año incluido',
    ],
    tiempoEntregaDias: 7,
    popular: false,
    activo: true,
  },
  {
    id: '2',
    nombre: 'Web Básica',
    tipo: 'web_basica',
    descripcion: 'Sitio web informativo para tu negocio',
    precio: 25000,
    caracteristicas: [
      'Hasta 5 páginas',
      'Diseño personalizado',
      'Responsive',
      'Formulario de contacto',
      'Mapa de ubicación',
      'Optimización SEO',
      'Hosting 1 año incluido',
    ],
    tiempoEntregaDias: 14,
    popular: false,
    activo: true,
  },
  {
    id: '3',
    nombre: 'Web Profesional',
    tipo: 'web_profesional',
    descripcion: 'Sitio web completo con funcionalidades avanzadas',
    precio: 45000,
    precioAnterior: 55000,
    caracteristicas: [
      'Hasta 10 páginas',
      'Diseño premium personalizado',
      'Panel de administración',
      'Blog integrado',
      'Galería de imágenes/videos',
      'Optimización SEO avanzada',
      'Integración redes sociales',
      'Hosting 1 año + dominio',
    ],
    tiempoEntregaDias: 21,
    popular: true,
    activo: true,
  },
  {
    id: '4',
    nombre: 'E-commerce',
    tipo: 'ecommerce',
    descripcion: 'Tienda en línea completa para vender tus productos',
    precio: 75000,
    caracteristicas: [
      'Catálogo de productos ilimitado',
      'Carrito de compras',
      'Pasarela de pagos',
      'Panel de administración',
      'Gestión de inventario',
      'Cupones y descuentos',
      'Reportes de ventas',
      'Hosting 1 año + dominio',
    ],
    tiempoEntregaDias: 30,
    popular: true,
    activo: true,
  },
  {
    id: '5',
    nombre: 'Aplicación Web',
    tipo: 'aplicacion',
    descripcion: 'Aplicación web personalizada para tu negocio',
    precio: 120000,
    caracteristicas: [
      'Desarrollo a medida',
      'Diseño UI/UX profesional',
      'Panel de administración',
      'API integrada',
      'Base de datos',
      'Escalable',
      'Soporte técnico 3 meses',
    ],
    tiempoEntregaDias: 60,
    popular: false,
    activo: true,
  },
];

export const mockMetricas: MetricasDashboard = {
  ingresosMes: 285000,
  ingresosMesAnterior: 245000,
  proyectosActivos: 4,
  ticketsAbiertos: 3,
  leadsNuevos: 23,
  tasaConversion: 12.5,
  ventasPorVendedor: [
    {
      vendedorId: '2',
      vendedorNombre: 'Ana García',
      ventas: 165000,
      meta: 150000,
      comisiones: 16500,
    },
    {
      vendedorId: '3',
      vendedorNombre: 'Miguel López',
      ventas: 120000,
      meta: 120000,
      comisiones: 12000,
    },
  ],
  ingresosPorMes: [
    { mes: 'Jul', ingresos: 180000, egresos: 85000, neto: 95000 },
    { mes: 'Ago', ingresos: 210000, egresos: 95000, neto: 115000 },
    { mes: 'Sep', ingresos: 195000, egresos: 88000, neto: 107000 },
    { mes: 'Oct', ingresos: 230000, egresos: 102000, neto: 128000 },
    { mes: 'Nov', ingresos: 245000, egresos: 98000, neto: 147000 },
    { mes: 'Dic', ingresos: 285000, egresos: 115000, neto: 170000 },
  ],
  proyectosPorEstado: [
    { estado: 'pendiente', cantidad: 1 },
    { estado: 'en_desarrollo', cantidad: 3 },
    { estado: 'en_revision', cantidad: 0 },
    { estado: 'entregado', cantidad: 1 },
    { estado: 'cancelado', cantidad: 0 },
  ],
};

export const currentUser = mockUsers[0]; // Admin por defecto
